### PR TITLE
add Number of Students Doing Homework at a Given Time

### PR DESCRIPTION
**Pull request by tkkawa**
n = startTime.length
time : O(n)
space : O(1)

### CODE REVIEW

**Review by ryuji0123 — CHANGES_REQUESTED** [review]
Your space & time complexities are correct.

Now you should use list comprehension

```
class Solution:
    def busyStudent(self, startTime: List[int], endTime: List[int], queryTime: int) -> int:
        return sum([st <= queryTime <= et for st, et in zip(startTime, endTime)])
```

**Review by ryuji0123 — APPROVED** [review]
LGTM

**Review by Akiiiira — APPROVED** [review]
LGTM
very sharp answer

**Comment by ryuji0123** [comment]
@Akiiiira 
Thanks

**Pull request merged**
