### PR TITLE
add Cells with Odd Values in a Matrix

### PR DESCRIPTION
**Pull request by tkkawa**
time : O(N) ( N=max(n*m, indices.length) )
space : O(1)

### CODE REVIEW

**Review by ryuji0123 — CHANGES_REQUESTED** [review]
You can reduce your code like this

```
# time: O(nm)
# space: O(len(indices))
from collections import defaultdict
class Solution:
    def oddCells(self, n: int, m: int, indices: List[List[int]]) -> int:
        rows = defaultdict(int)
        cols = defaultdict(int)
        for r, c in indices:
            rows[r] += 1
            cols[c] += 1
             
        ret = 0
        for r in range(n):
            for c in range(m):
                ret += (rows[r] + cols[c]) % 2
        return ret 
```

**Comment by ryuji0123** [comment]
Also 
```
indices.length <= n + m
time: O(max(nm, n+m))
```

**Review by ryuji0123 — APPROVED** [review]
LGTM

**Comment by Akiiiira** [comment]
LGTM

**Review by Akiiiira — APPROVED** [review]

**Pull request merged**
