### PR TITLE
add Maximum Depth of Binary Tree

### PR DESCRIPTION
**Pull request by tkkawa**
n = tree.length
time : O(logn)
space : O(1)

### CODE REVIEW

**Review by ryuji0123 — CHANGES_REQUESTED** [review]
```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, x):
#         self.val = x
#         self.left = None
#         self.right = None

class Solution:
    def maxDepth(self, root: TreeNode) -> int:
        if root is None:
            return 0
        return max(self.maxDepth(root.left) + 1, self.maxDepth(root.right) + 1)
```

**Comment by tkkawa** [comment]
I modified time, space complexity and code.
Please check them.

**Comment by ryuji0123** [comment]
e = 2v
You do not create any instances.
time: O(v)
space: O(1)

**Comment by ryuji0123** [comment]
e = 2v
time: O(v)
space: O(n) 
FYI: https://stackoverflow.com/questions/43298938/space-complexity-of-recursive-function

**Review by ryuji0123 — CHANGES_REQUESTED** [review]
determine edge order (I wrote in comments)

**Comment by tkkawa** [comment]
> determine edge order (I wrote in comments)

Edge order is 2^n
( n = maxDepth )

**Comment by ryuji0123** [comment]
> Edge order is 2^n
( n = maxDepth )

Why do you think so?

**Review by ryuji0123 — APPROVED** [review]
LGTM

**Review by Akiiiira — APPROVED** [review]
LGTM

**Pull request merged**
