### PR TITLE
add Matrix Diagonal Sum

### PR DESCRIPTION
**Pull request by tkkawa**
time complexity = O(n^3)
space complexity = O(1)

### CODE REVIEW

**Comment by ryuji0123** [comment]
You can improve your code like this
time: O(H) (H=len(mat))
space: O(1)

```
class Solution:
    def diagonalSum(self, mat: List[List[int]]) -> int:
        ret = 0
        left, right = -1, len(mat[0])
        for i in range(len(mat)):
            ret += mat[i][left+1] + mat[i][right-1] if left + 1 != right - 1 else mat[i][left+1]
            left += 1
            right -= 1
        return ret
```

**Review by ryuji0123 — CHANGES_REQUESTED** [review]
time: O(N^3logN)
space: O(1)

```
for i in range(mat_size): # O(N)
            for j in range(mat_size): # O(N)
                if i == j:
                    ret += mat[i][j]
                    mat[i].reverse() # O(N^1/2 * logN^1/2)
                    ret += mat[i][j]
```

**Comment by tkkawa** [comment]
reverse()のところがなぜ0(N^1/2)なのかわからないです

**Comment by ryuji0123** [comment]
```
H = len(mat)
W = len(mat[0])
N = HW
H = W = N^1/2
```

**Comment by ryuji0123** [comment]
```
mat[i].reverse() # O(W) = O(N^1/2)
```

**Review by ryuji0123 — APPROVED** [review]
LGTM!

**Comment by ryuji0123** [comment]
@tkkawa 
You can merge this branch when @Akiiiira approves it.

**Comment by ryuji0123** [comment]
Sorry, I misunderstood notations. Time complexity is O(N^3) since
```
H = W = N = len(mat)
mat[i].reverse() # O(W) = O(N)
```

Also, please write your notations when you show complexities.

**Comment by tkkawa** [comment]
あ、理解した。
上で奥田が書いてくれたコードだとfor文のところもO(w)なのか

**Comment by tkkawa** [comment]
thanks!

**Comment by Akiiiira** [comment]
LGTM

**Review by Akiiiira — COMMENTED** [review]
please tell me How to approve 
I can't recognize check box of approve when I push review changes button.

**Pull request merged**
